# Generated by Django 5.1.2 on 2025-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="uploads/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "files",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("medicine_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("dosage_med", models.CharField(blank=True, max_length=100, null=True)),
                ("quantite", models.CharField(blank=True, max_length=100, null=True)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "condition_si",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="core.file",
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reminder_time", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        db_column="prescription_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.TextField()),
                ("translated_text", models.TextField(blank=True, null=True)),
                (
                    "language_from",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("language_to", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.file",
                    ),
                ),
            ],
            options={
                "db_table": "translations",
            },
        ),
    ]
