# Generated by Django 5.1.2 on 2025-11-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
