# Generated by Django 5.1.2 on 2025-11-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prescription_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("blood_type", models.CharField(blank=True, max_length=10, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("chronic_conditions", models.TextField(blank=True, null=True)),
                ("surgeries", models.TextField(blank=True, null=True)),
                ("family_history", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "doctor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_profile",
                        to="core.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "medical_profiles",
            },
        ),
    ]
