# Generated by Django 5.1.2 on 2025-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_medicalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="reminder_photos/"
            ),
        ),
    ]
