# Generated by Django 5.1.2 on 2026-01-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_reminder_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("taken", "Pris"),
                    ("skipped", "Ignoré"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
