# Generated by Django 5.1.2 on 2026-03-05 15:13

import encrypted_model_fields.fields
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_is_active_to_appuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=core.models.File._get_upload_path),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="social_security_number",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
